name: SERBAN
favicon: null
layout_spectrum: 0.0462819563690573
typography_spectrum: 0.8052975579630584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9417227616067976
  lightness: 0.11741631664335728
  saturation: 0.5333018563687801
  rhythmicContrast: 0.9263909894507378
purpose: []
